
# Название workflow
name: tretyakovgallery test

# Триггеры для запуска workflow
on:
  # Автоматический запуск workflow по расписанию (в полночь каждый день)
  schedule:
    - cron: "0 0 * * *"
  # Ручной запуск workflow
  workflow_dispatch:
    
# Задание для workflow
jobs:
  autotests: 
    # Время ожидания для задания (60 минут)
    timeout-minutes: 60
    # Среда для выполнения задания (Ubuntu)
    runs-on: ubuntu-latest

    # Шаги для задания
    steps: 
      - name: Checkout code
      - uses: actions/checkout@v4
      - name: Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      # Установка зависимостей проекта
      - run: npm i
      - name: Install playwright    
        run: npx playwright install --with-deps
        
      # Запуск тестов
      - name: Run playwright test
        run: npm run test

      # Загрузка результатов тестов
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: test-results 
          path: test-results
          retentions-days: 20

      # Загрузка результатов тестов Allure    
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-results 
          path: allure-results
          retentions-days: 20
   
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Генерация отчета Allure
      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure-results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      - name: Deploy report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env: 
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH:  gh-pages
          PUBLISH_DIR:  allure-history
          
          
  
  
