name: tretyakovgallery test
on:
  push: 
    branches: [main, master]
  pull_request:   
    branches: [main, master]
  workflow_dispatch:
jobs:
  test: 
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps: 
      - uses: action/checkout@v4
      - uses: action/setup-node@v4
        with:
          node-version: lts/*
      - name: install PW    
        run: npx playwright install --with-deps
      - name: Run PW test
        run: npx run test
    
    
  
  
